export const pyqFilters = [
  {
    id: 'semester',
    name: 'Semester',
    options: [
      { value: 'first', label: 'First Semester', checked: false },
      { value: 'second', label: 'Second Semester', checked: false },
      { value: 'third', label: 'Third Semester', checked: false },
      { value: 'fourth', label: 'Fourth Semester', checked: false },
      { value: 'fifth', label: 'Fifth Semester', checked: false },
      { value: 'sixth', label: 'Sixth Semester', checked: false },
      { value: 'seventh', label: 'Seventh Semester', checked: false },
      { value: 'eight', label: 'Eight Semester', checked: false },
    ],
  },
  {
    id: 'subjectcode',
    name: 'Subject Code',
    options: [
      { value: 'CS101', label: 'CS101', checked: false },
      { value: 'CS102', label: 'CS102', checked: false },
      { value: 'CS201', label: 'CS201', checked: false },
      { value: 'CS202', label: 'CS202', checked: false },
      { value: 'CS301', label: 'CS301', checked: false },
      { value: 'CS302', label: 'CS302', checked: false },
      { value: 'CS401', label: 'CS401', checked: false },
      { value: 'CS402', label: 'CS402', checked: false },
      { value: 'MTH101', label: 'MTH101', checked: false },
      { value: 'MTH102', label: 'MTH102', checked: false },
      { value: 'MTH201', label: 'MTH201', checked: false },
      { value: 'MTH202', label: 'MTH202', checked: false },
      { value: 'PHY101', label: 'PHY101', checked: false },
      { value: 'PHY102', label: 'PHY102', checked: false },
      { value: 'ENG101', label: 'ENG101', checked: false },
      { value: 'ENG102', label: 'ENG102', checked: false },
      { value: 'HUCS101', label: 'HUCS101', checked: false },
    ],
  },
  {
    id: 'exam',
    name: 'Exam Type',
    options: [
      { value: 'mst1', label: 'MST 1', checked: false },
      { value: 'mst2', label: 'MST 2', checked: false },
      { value: 'endsem', label: 'End Semester', checked: false },
    ],
  },
];

export const notesFilters = [
  {
    id: 'semester',
    name: 'Semester',
    options: [
      { value: 'first', label: 'First Semester', checked: false },
      { value: 'second', label: 'Second Semester', checked: false },
      { value: 'third', label: 'Third Semester', checked: false },
      { value: 'fourth', label: 'Fourth Semester', checked: false },
      { value: 'fifth', label: 'Fifth Semester', checked: false },
      { value: 'sixth', label: 'Sixth Semester', checked: false },
      { value: 'seventh', label: 'Seventh Semester', checked: false },
      { value: 'eight', label: 'Eight Semester', checked: false },
    ],
  },
  {
    id: 'subjectcode',
    name: 'Subject Code',
    options: [
      { value: 'CS101', label: 'CS101', checked: false },
      { value: 'CS102', label: 'CS102', checked: false },
      { value: 'CS201', label: 'CS201', checked: false },
      { value: 'CS202', label: 'CS202', checked: false },
      { value: 'CS301', label: 'CS301', checked: false },
      { value: 'CS302', label: 'CS302', checked: false },
      { value: 'CS401', label: 'CS401', checked: false },
      { value: 'CS402', label: 'CS402', checked: false },
      { value: 'MTH101', label: 'MTH101', checked: false },
      { value: 'MTH102', label: 'MTH102', checked: false },
      { value: 'MTH201', label: 'MTH201', checked: false },
      { value: 'MTH202', label: 'MTH202', checked: false },
      { value: 'PHY101', label: 'PHY101', checked: false },
      { value: 'PHY102', label: 'PHY102', checked: false },
      { value: 'ENG101', label: 'ENG101', checked: false },
      { value: 'ENG102', label: 'ENG102', checked: false },
      { value: 'HUCS101', label: 'HUCS101', checked: false },
    ],
  },
];
